language: perl
perl:
   - "5.8"
   - "5.10"
   - "5.12"
   - "5.14"
   - "5.16"
   - "5.18"
   - "5.20"
   - "5.22"
   - "5.24"
   - "blead"

matrix:
  allow_failures:
    - perl: "blead"

before_install:
   - git clone git://github.com/haarg/perl-travis-helper
   - source perl-travis-helper/init
   - build-perl
   - perl -V

   - sudo /etc/init.d/mysql restart
   - mysql -e 'create database dbii_test;'
   - export DBIITEST_MYSQL_DSN='dbi:mysql:database=dbii_test;host=127.0.0.1'
   - export DBIITEST_MYSQL_USER=root

   - sudo /etc/init.d/postgresql restart
   - psql -c 'create database dbii_test;' -U postgres
   - export DBIITEST_PG_DSN='dbi:Pg:database=dbii_test;host=127.0.0.1'
   - export DBIITEST_PG_USER=postgres

   - /bin/sync

install:
   - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=c HARNESS_TIMER=1
   - cpanm --quiet --notest Devel::Cover::Report::Coveralls SQL::Translator DBD::Pg DBD::mysql DateTime::Format::Pg DateTime::Format::MySQL
   - cpanm --quiet --notest --installdeps .
   - perl -Ilib -It/lib -MTestSchema -e'TestSchema->generate_ddl'

script:
   - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -lrsv t
   - cover
after_success:
  - cover -report coveralls
